import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

const sidebars: SidebarsConfig = {
  // 手动定义侧边栏结构
  tutorialSidebar: [
    {
          type: 'category',
          label: 'Tokenized Stock Products',
          items: [
            'products/xstocks/aaplx',
        'products/xstocks/abbvx',
        'products/xstocks/abtx',
        'products/xstocks/acnx',
        'products/xstocks/ambrx',
        'products/xstocks/amznx',
        'products/xstocks/appx',
        'products/xstocks/avgox',
        'products/xstocks/aznx',
        'products/xstocks/bacx',
        'products/xstocks/brkbx',
        'products/xstocks/cmcsax',
        'products/xstocks/coinx',
        'products/xstocks/crclx',
        'products/xstocks/crmx',
        'products/xstocks/crwdx',
        'products/xstocks/cscox',
        'products/xstocks/cvxx',
        'products/xstocks/dfdvx',
        'products/xstocks/dhrx',
        'products/xstocks/gldx',
        'products/xstocks/gmex',
        'products/xstocks/googlx',
        'products/xstocks/gsx',
        'products/xstocks/hdx',
        'products/xstocks/honx',
        'products/xstocks/hoodx',
        'products/xstocks/ibmx',
        'products/xstocks/intcx',
        'products/xstocks/jnjx',
        'products/xstocks/jpmx',
        'products/xstocks/kox',
        'products/xstocks/linx',
        'products/xstocks/llyx',
        'products/xstocks/max',
        'products/xstocks/mcdx',
        'products/xstocks/mdtx',
        'products/xstocks/metax',
        'products/xstocks/mrkx',
        'products/xstocks/mrvlx',
        'products/xstocks/msftx',
        'products/xstocks/mstrx',
        'products/xstocks/nflxx',
        'products/xstocks/nvdax',
        'products/xstocks/nvox',
        'products/xstocks/orclx',
        'products/xstocks/pepx',
        'products/xstocks/pfex',
        'products/xstocks/pgx',
        'products/xstocks/pltrx',
        'products/xstocks/pmx',
        'products/xstocks/qqqx',
        'products/xstocks/spyx',
        'products/xstocks/tmox',
        'products/xstocks/tqqqx',
        'products/xstocks/tslax',
        'products/xstocks/unhx',
        'products/xstocks/vx',
        'products/xstocks/vtix',
        'products/xstocks/wmtx',
        'products/xstocks/xomx',
      ],
    },


    'faq',
    'compliance',
    {
      type: 'category',
      label: 'Legal Documents',
      items: [
        'legal/privacy-policy',
        'legal/disclaimer',
        'legal/affiliate-disclosure',
      ],
    },
  ],
};

export default sidebars;
