name: Scrape XStocks Data

on:
  schedule:
    # 每天UTC时间02:00执行 (北京时间10:00)
    - cron: '0 2 * * *'
  workflow_dispatch: # 允许手动触发
  push:
    paths:
      - 'scripts/scrape-xstocks.js'
      - '.github/workflows/scrape-data.yml'

jobs:
  scrape-and-update:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: |
        npm ci
        npm install cheerio
        
    - name: Create required directories
      run: |
        mkdir -p docs/products
        mkdir -p static/img/tokens
        mkdir -p data
        
    - name: Run scraping script
      run: |
        node scripts/scrape-xstocks.js
        
    - name: Check for changes
      id: verify-changed-files
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          echo "changed=true" >> $GITHUB_OUTPUT
        else
          echo "changed=false" >> $GITHUB_OUTPUT
        fi
        
    - name: Commit and push changes
      if: steps.verify-changed-files.outputs.changed == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "🤖 Auto-update: Scraped latest tokenized stock data from xstocks.com
        
        - Updated product information
        - Updated compliance data
        - Downloaded latest token logos
        
        Generated at: $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
        git push
        
    - name: Create summary
      if: always()
      run: |
        echo "## 📊 Scraping Summary" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "- **Execution Time**: $(date -u '+%Y-%m-%d %H:%M:%S UTC')" >> $GITHUB_STEP_SUMMARY
        echo "- **Status**: ${{ job.status }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Changes Detected**: ${{ steps.verify-changed-files.outputs.changed }}" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        
        if [ -f "data/products.json" ]; then
          PRODUCT_COUNT=$(jq length data/products.json)
          echo "- **Products Found**: $PRODUCT_COUNT" >> $GITHUB_STEP_SUMMARY
        fi
        
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### 📁 Updated Files" >> $GITHUB_STEP_SUMMARY
        git diff --name-only HEAD~1 2>/dev/null | head -20 | while read file; do
          echo "- \`$file\`" >> $GITHUB_STEP_SUMMARY
        done || echo "- No changes detected" >> $GITHUB_STEP_SUMMARY
        
    - name: Notify on failure
      if: failure()
      run: |
        echo "❌ Scraping failed. Please check the logs and update the script if needed."
        echo "Common issues:"
        echo "- Website structure changed"
        echo "- Network connectivity issues"
        echo "- Rate limiting"
        echo "- Missing dependencies"